mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
                  path('service/', include('service.urls')),
                  path('admin/', admin.site.urls),
                  path('', RedirectView.as_view(url='service/', permanent=True)),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('tinymce/', include('tinymce.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path

from . import views
from django.conf.urls import include

urlpatterns = [
    path('', views.index, name='index'),
    path('automobiliai/', views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:automobilis_id>', views.automobilis, name='automobilis'),
    path('paslaugos/', views.paslaugos, name='paslaugos'),
    path('uzsakymai/', views.UzsakymasListView.as_view(), name='uzsakymai'),
    path('uzsakymai/<int:pk>', views.UzsakymasDetailView.as_view(), name='uzsakymas-detail'),
    path('myorders/', views.VartotojoUzsakymuListView.as_view(), name='my-in-progress'),
    path('uzsakymai/naujas', views.VartotojoUzsakymuCreateView.as_view(), name='naujas-manouzsakymas'),
    path('uzsakymai/<int:pk>/redaguoti', views.VartotojoUzsakymuUpdateView.as_view(), name='manouzsakymas-redaguoti'),
    path('uzsakymai/<int:pk>/redaguotiuzsakyma', views.UzsakymoUpdateView.as_view(), name='uzsakymas-redaguoti'),
    path('uzsakymai/<int:pk>/istrinti', views.VartotojoUzsakymuDeleteView.as_view(), name="manouzsakymas-istrinti"),
    path('uzsakymai/<int:pk>/istrintiuzsakyma', views.UzsakymoDeleteView.as_view(), name="uzsakymas-istrinti"),
    path("uzsakymai/<int:pk>/pridetieilute", views.VartotojoEilutesCreateView.as_view(), name="uzsakymai_pridetieilute"),
    path("uzsakymai/<int:uzsakymai_pk>/redaguotieilute/<int:pk>", views.VartotojoEilutesUpdateView.as_view(),
         name="uzsakymai_redaguotieilute"),
    path("uzsakymai/<int:uzsakymai_pk>/istrintieilute/<int:pk>", views.VartotojoEilutesDeleteView.as_view(),
         name="uzsakymai_istrintieilute"),
    path('search/', views.search, name='search'),
    path('logout/', views.CustomLogout.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('i18n/', include('django.conf.urls.i18n')),
]

service/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _


class AutomobilioModelis(models.Model):
    marke = models.CharField(_('Make'), max_length=100)
    modelis = models.CharField(_('Model'), max_length=100)
    metai = models.CharField(_('Year'), max_length=4)
    variklis = models.CharField(_('Engine'), max_length=10)

    def __str__(self):
        return f'{self.marke} {self.modelis} ({self.metai}, {self.variklis})'

    class Meta:
        verbose_name = _('Car model')
        verbose_name_plural = _('Car models')


class Paslauga(models.Model):
    pavadinimas = models.CharField(_('cdName'), max_length=100, help_text=_('Enter the name of the service (eg oil change)'))
    paslaugos_kaina = models.DecimalField(_('Price'), max_digits=12, decimal_places=2, help_text=_('Enter the price of the service'))

    def __str__(self):
        return f'{self.pavadinimas}'

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')


class Automobilis(models.Model):
    valstybinis_nr = models.CharField(_('License Plate'), max_length=7)
    automobilio_modelis = models.ForeignKey(to=AutomobilioModelis, on_delete=models.SET_NULL, null=True, verbose_name='Automobilis')
    vin_kodas = models.CharField(_('VIN code'), max_length=20)
    klientas = models.CharField(_('Customer'), max_length=20)
    cover = models.ImageField(_('Photo'), upload_to='automobiliai', null=True)
    aprasymas = HTMLField(_('Description'), default='')

    def __str__(self):
        return f'{self.valstybinis_nr} | {self.automobilio_modelis}'

    class Meta:
        verbose_name = _('Vehicle')
        verbose_name_plural = _('Vehicles')


class Uzsakymas(models.Model):
    data = models.DateTimeField(_('Date'), auto_now_add=True)
    automobilis = models.ForeignKey(to="Automobilis", verbose_name=_("Vehicle"), on_delete=models.CASCADE)
    # suma = models.DecimalField('Suma', max_digits=12, decimal_places=2, default=0, null=True)
    aprasymas = HTMLField(_('Description of the problem'), default='')
    vartotojas = models.ForeignKey(to=User, verbose_name=_("User"), on_delete=models.SET_NULL, null=True, blank=True)
    terminas = models.DateField(_('Deadline'), null=True, blank=True)

    @property
    def ar_baigesi_terminas(self):
        if self.terminas and date.today() > self.terminas:
            return True
        return False

    def suma(self):
        suma = 0
        eilutes = self.uzsakymo_eilutes.all()
        for eilute in eilutes:
            suma += eilute.kaina()
        return suma

    LOAN_STATUS = (
        ('p', _("Confirmed")),
        ('v', _("In Progress")),
        ('i', _("Done")),
        ('a', _("Canceled")),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='p',
        help_text=_("Status"),
    )

    # def save(self):
    #     suma = 0
    #     eilutes = self.uzsakymo_eilutes.all()
    #     for eilute in eilutes:
    #         suma += eilute.kaina()
    #     self.suma = suma
    #     super().save()

    def __str__(self):
        return f"{self.data.strftime('%Y-%m-%d %H:%M:%S')} >>> {self.automobilis}"

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
        ordering = ['-data']


class UzsakymoEilute(models.Model):
    paslauga = models.ForeignKey(to="Paslauga", verbose_name=_("Service"), on_delete=models.SET_NULL, null=True)
    uzsakymas = models.ForeignKey(to="Uzsakymas", verbose_name=_("Order"), on_delete=models.CASCADE, related_name='uzsakymo_eilutes')
    kiekis = models.IntegerField(_("Quantity"))
    # kaina = models.DecimalField('Kaina', max_digits=12, decimal_places=2, default=0, null=True)

    def __str__(self):
        return f'{self.uzsakymas.data} - {self.paslauga}'

    def kaina(self):
         return self.kiekis * self.paslauga.paslaugos_kaina

    # def save(self):
    #     self.kaina = self.kiekis * self.paslauga.paslaugos_kaina
    #     super().save()

    class Meta:
        verbose_name = _("Orderline")
        verbose_name_plural = _("Orderlines")


class UzsakymuAtsiliepimai(models.Model):
    uzsakymas = models.ForeignKey(to="Uzsakymas", verbose_name=_("Order"), on_delete=models.SET_NULL, null=True, blank=True)
    komentatorius = models.ForeignKey(to=User, verbose_name=_("Commentator"), on_delete=models.SET_NULL, null=True, blank=True)
    sukurimo_data = models.DateTimeField(auto_now_add=True)
    atsiliepimas = models.TextField(_("Comment"), max_length=2000)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['-sukurimo_data']


class Profilis(models.Model):
    user = models.OneToOneField(to=User, verbose_name=_("User"), on_delete=models.CASCADE)
    nuotrauka = models.ImageField(verbose_name=_("Photo"), default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

service/forms.py
from .models import UzsakymuAtsiliepimai, Profilis, Uzsakymas
from django import forms
from django.contrib.auth.models import User


class UzsakymuAtsiliepimaiForm(forms.ModelForm):
    class Meta:
        model = UzsakymuAtsiliepimai
        fields = ('atsiliepimas', 'uzsakymas', 'komentatorius')
        widgets = {'uzsakymas': forms.HiddenInput(), 'komentatorius': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']


class DateInput(forms.DateTimeInput):
    input_type = "date"


class VartotojoUzsakymuCreateForm(forms.ModelForm):
    class Meta:
        model = Uzsakymas
        fields = ['automobilis', 'terminas', 'status']
        widgets = {'vartotojas': forms.HiddenInput(), 'terminas': DateInput()}

service/templates/automobilis.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div style="margin-left:10px;margin-top:20px">
    {% load static %}
    <div class="col-md-4 d-flex align-items-stretch">
        {% if automobilis.cover %}
        <img src="{{ automobilis.cover.url }}" class="card-img-top" alt="...">
        {% else %}
        <img src="{% static 'img/cover.jpg' %}" class="card-img-top">
        {% endif %}
    </div>
    <div style="margin-left:10px;margin-top:20px">
        <h3>{% trans "License Plate:" %} {{ automobilis.valstybinis_nr }}</h3>
    </div>
    <hr/>
    <p><strong>{% trans "Customer:" %}</strong> {{ automobilis.klientas }}</p>
    <p><strong>{% trans "Vehicle:" %}</strong> {{ automobilis.automobilio_modelis }}</p>
    <p><strong>{% trans "VIN code:" %}</strong> {{ automobilis.vin_kodas }}</p>
    </hr>
    <hr/>
    <p><strong>{% trans "Description:" %}</strong> {{ automobilis.aprasymas | safe }}</p>
    </hr>

</div>
{% endblock %}

service/templates/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="lt">
<head>
  {% block title %}<title>{% trans "Autoservice" %}</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" height="30" ></a></li>
<!--          <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Pradžia</a></li>-->
          <li class="nav-item active"><a class="nav-link" href="{% url 'automobiliai' %}">{% trans "Vehicles" %}</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'paslaugos' %}">{% trans "Services" %}</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'uzsakymai' %}">{% trans "Orders" %}</a></li>
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'my-in-progress'%}">{% trans "My orders" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'naujas-manouzsakymas' %}">{% trans "New order" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">{% trans "Logout" %}</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}">{% trans "Login" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">{% trans "Register" %}</a></li>
          {% endif %}
        </ul>
      {% load i18n %}
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.1 }} ({{ lang.0 }})
          </option>
          {% endfor %}
        </select>
        <input type="submit" value="Go"/>
      </form>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
      <input class="form-control mr-sm-2" name="query" class="form-control" type="text" placeholder="{% blocktrans %} Search {% endblocktrans %}">
      </form>
    </nav>
    {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                  {{ message }}
          </div>
      {% endfor %}
    {% endif %}
    <div class="col-sm-10 ">
        {% block content %}
        {% endblock %}
    </div>
  </div>
</body>
</html>

service/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
  <img src="{% static 'img/auto.png' %}" class="img-fluid">
<div style="margin-left:100px;margin-top:20px">
  <h1>VIP {% trans "Autoservice" %}</h1>
  <div style="margin-left:70px;margin-top:60px">
    <h5>{% trans "My Autoservice statistics:" %}</h5>
  <ul>
    <li><strong>{% trans "Services:" %}</strong> {{ num_paslaugos }}</li>
    <li><strong>{% trans "Orders done:" %}</strong> {{ num_uzsakymai }}</li>
    <li><strong>{% trans "Registered Vehicles:" %}</strong> {{ num_auto }}</li>
    <li><strong>{% trans "Visits:" %}</strong> {{ num_visits }}</li>
  </ul>
  </div>
</div>
{% endblock %}

service/templates/order_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{% trans "Delete order" %}</legend>
            <h2>{% trans "Are you sure want to delete the order" %} {{ uzsakymas }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">{% trans "Yes, delete" %}</button>
            <a class="btn btn-outline-secondary" href="{% url 'uzsakymai' %}">{% trans "Cancel" %}</a>
        </div>
    </form>
    </div>
{% endblock content %}

service/templates/paslaugos.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
  <img src="{% static 'img/paslaugos.png' %}" class="img-fluid">
  <h1>{% trans "Services" %}</h1>
  <p>{% trans "List of our services:" %}</p>
  {% for paslauga in paslaugos %}
    <li><strong>{{paslauga.pavadinimas}}</strong>, {% trans "price:" %} {{paslauga.paslaugos_kaina}} Eur</li>
    {% endfor %}
  <div class="container puslapiai">
      <nav aria-label="...">
          {% if paslaugos.has_other_pages %}
              <ul class="pagination pagination-sm justify-content">
                  {% for i in paslaugos.paginator.page_range %}
                      {% if paslaugos.number == i %}
                          <li class="page-item active">
                              <a class="page-link">{{ i }}</a>
                          </li>
                      {% else %}
                          <li class="page-item">
                              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                          </li>
                      {% endif %}
                  {% endfor %}
              </ul>
          {% endif %}
      </nav>
  </div>
{% endblock %}

service/templates/register.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

    <div class="container register">
        <h3>{% trans "Registration" %}</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">{% trans "User name" %}</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">{% trans "Up to 150 characters." %}</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">{% trans "E-mail" %}</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">{% trans "Required to send a new password." %}</small>
            </div>
            <div class="form-group">
                <label for="password">{% trans "Password" %}</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">{% trans "At least 8 characters. It can't just be numbers." %}</small>
            </div>
            <div class="form-group">
                <label for="password2">{% trans "Repeat the password" %}</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">{% trans "Register" %}</button>
        </form>
        <p>{% trans "If you have registered before," %} <a href="{% url 'login'%}"><strong>{% trans "sign in." %}</strong></a></p>
    </div>

{% endblock %}

service/templates/search.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% blocktrans %}Query "{{query}}" results:{% endblocktrans %}</h1>
  </br>
  {% if automobiliai %}
  <ul>
    {% for automobilis in automobiliai %}
      <li>
        <a href="{% url 'automobilis' automobilis.id %}">{{ automobilis.automobilio_modelis }}</a> (užsakovas: {{automobilis.klientas}}, valstybinis Nr. {{automobilis.valstybinis_nr}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>{% trans "Oops. No results" %}</p>
  {% endif %}

  {% endblock %}

service/templates/user_order.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
<img src="{% static 'img/user_order.png' %}" class="img-fluid">
<div style="margin-left:10px;margin-top:20px">
    <h1>{% trans "My orders:" %}</h1>

    {% if uzsakymas_list %}
        <table class="table table-borderless" style="color:white">
        <tbody>
        {% for uzsakymas in uzsakymas_list %}
            <tr>
                <td><img class="rounded-circle" src="{{ user.profilis.nuotrauka.url }}" height="50"></td>
                <td class="align-middle fs-4 ">
                    <li class="{% if uzsakymas.ar_baigesi_terminas %}text-danger{% endif %}"> {{uzsakymas}} / {% trans "deadline" %} >>>> {{ uzsakymas.terminas }}
                    <a class="btn btn-primary" href="{% url 'uzsakymas-detail' uzsakymas.pk %}" role="button">{% trans "View" %}</a>
                        {% if uzsakymas.vartotojas == user %}
                        <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'manouzsakymas-redaguoti' uzsakymas.id %}">{% trans "Edit" %}</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'manouzsakymas-istrinti' uzsakymas.id %}">{% trans "Delete" %}</a>
                        </div>
                        {% endif %}
                    </li>
                </td>
            </tr>
        {% endfor%}
        </tbody>
    </table>


    {% else %}
      <p>{% trans "No orders available." %}</p>
    {% endif %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; {% trans "first" %}</a>
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "back" %}</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{% trans "forward" %}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "last" %} &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endblock %}

service/templates/user_order_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{% trans "Delete order" %}</legend>
            <h2>{% trans "Are you sure want to delete the order" %} {{ uzsakymas }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">{% trans "Yes, delete" %}</button>
            <a class="btn btn-outline-secondary" href="{% url 'my-in-progress' %}">{% trans "Cancel" %}</a>
        </div>
    </form>
    </div>
{% endblock content %}

service/templates/uzsakymas_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{{ uzsakymas.id }} | {{ uzsakymas.data }}</h1>

  <div style="margin-top:50px">
    <img class="rounded-circle account-img" src="{{ uzsakymas.vartotojas.profilis.nuotrauka.url }}" height="100">
    <p><strong>{% trans "User:" %}</strong> {{ uzsakymas.vartotojas }}</p>
    <p><strong>{% trans "Vehicle:" %}</strong> {{ uzsakymas.automobilis }}</p>
    <p><strong>{% trans "Order total:" %}</strong> {{ uzsakymas.suma }}</p>
    <p><strong>{% trans "Status:" %}</strong> {{ uzsakymas.get_status_display }}</p>
    <p><strong>{% trans "Deadline:" %}</strong> {{ uzsakymas.terminas }}</p>
    {% if uzsakymas.vartotojas == user %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'uzsakymas-redaguoti' uzsakymas.id %}">{% trans "Edit" %}</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'uzsakymas-istrinti' uzsakymas.id %}">{% trans "Delete" %}</a>
        </div>
    {% endif %}
    <hr/>
    </hr>
    <p><strong>{% trans "Problem description:" %}</strong></p>
    <p>{{ uzsakymas.aprasymas | safe }}</p>
    <hr/>
    </hr>
  </div>
  <div style="margin-left:20px;margin-top:20px">
      <h4>{% trans "Order details:" %}</h4>
  <table class="table table-dark table-sm">
        <thead>
            <tr>
                <th>{% trans "Service" %}</th>
                <th>{% trans "Quantity, pcs" %}</th>
                <th>{% trans "Price, EUR" %}</th>
                <th>{% trans "SUM, EUR" %}</th>
                {% if uzsakymas.vartotojas == user %}
                <th scope="col"></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for eilute in uzsakymas.uzsakymo_eilutes.all %}
            <tr>
                <td>{{ eilute.paslauga.pavadinimas }}</td>
                <td>{{ eilute.kiekis }}</td>
                <td>{{ eilute.paslauga.paslaugos_kaina }}</td>
                <td>{{ eilute.kaina }}</td>
                {% if uzsakymas.vartotojas == user %}
                <td scope="row">
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'uzsakymai_redaguotieilute' uzsakymas.id eilute.id %}">{% trans "Edit" %}</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'uzsakymai_istrintieilute' uzsakymas.id eilute.id %}">{% trans "Delete" %}</a>
                    </div>
        </td>
        {% endif %}
            </tr>
        {% endfor%}
        </tbody>
    </table>
    {% if uzsakymas.vartotojas == user %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'uzsakymai_pridetieilute' uzsakymas.id %}">{% trans "Add line" %}</a>
        </div>
    {% endif %}
  </div>
</br>
<hr style="height:5px;border-width:0;background-color:red">
  <h4>{% trans "Comments:" %}</h4>
  {% if uzsakymas.uzsakymuatsiliepimai_set.all %}
    {% for atsiliepimas in uzsakymas.uzsakymuatsiliepimai_set.all %}
      <hr style="width:50%">
      <strong>{{ atsiliepimas.komentatorius }}</strong>, <em>{{ atsiliepimas.sukurimo_data}}</em>
      <p>{{ atsiliepimas.atsiliepimas }}</p>
    {% endfor %}
  {% else %}
    <p>{% trans "No Comments" %}</p>
  {% endif %}

  {% if user.is_authenticated %}
      <div class="fieldWrapper">
        <hr><br/>
        <h4>{% trans "Leave a Comment:" %}</h4>
        <form action="" method="post">
          {% csrf_token %}
          {{ form.atsiliepimas }}</br>
          <input type="submit" value="{% blocktrans %} Save {% endblocktrans %}">
        </form>
      </div>
  {% endif %}
</hr>
{% endblock %}